### ISSUE TITLE
Intermittent Incorrect Time

### ISSUE THREAD

**Issue by linickx** [nobuhito/atom-statusbar-datetime#1]
Hi,

Any suggestions on how to debug this? Sporadically I get the wrong time... screenshot attached showing default update interval, time in status bar is 1010 where as time on system is 1048.

Thanks in Advance!

![statusbar-incorrect-datetime](https://cloud.githubusercontent.com/assets/649661/10451524/9fd195e4-7198-11e5-8465-743704c02f8f.png)

**Comment by nobuhito** [comment]
@linickx 
What if you specify "dddd HHmm"?
Please refer to the http://momentjs.com/docs/ for details.

**Comment by linickx** [comment]
ok, :confused: ... I'm sure I've seen it working, but that doc says that I've been using Month instead of Minute :blush: ... oh well, I'll see how that goes, thanks!

**Comment by nobuhito** [comment]
@linickx 
Added link for README.md and setting view.
Thank you for notice to me.

**Comment by linickx** [comment]
:+1:
